### PR TITLE
use rocket-dev main

### PR DESCRIPTION
**Pull request by staabm**
try to verify fix from https://github.com/rectorphp/rector/issues/6798#issuecomment-965527157

### CODE REVIEW

**Comment by TomasVotruba** [comment]
I'm unable to reproduce this locally, tests pass.

My steps:

```bash
git clone git@github.com:staabm/rector-view-scope.git
cd rector-view-scope
composer update
vendor/bin/phpunit
```

**Comment by staabm** [comment]
Ok cool. After clone you could also checkout this PRs branch.

But it seems to work already for you.

**Comment by TomasVotruba** [comment]
Yea, I forgot the PR checkout. Thanks :+1:

**Comment by TomasVotruba** [comment]
cc @samsonasik I managed to replicate here, no need for example, Just FIY :)

**Comment by TomasVotruba** [comment]
I think the scoper-autoload.php is missing in the test case.

**Comment by TomasVotruba** [comment]
Let's see :) https://github.com/rectorphp/rector-src/commit/cd217264b75e2b7ace93c46f346d32916e2d9809

**Comment by staabm** [comment]
it works for me now

**Pull request closed without merging**
